### ISSUE TITLE
No icon

### ISSUE THREAD

**Issue by maximedub** [rNeomy/proxy-switcher#1]
I try your plugin, but i have no icon... so I can't have interaction with the plugin.
If I initialise personalisation of firefox, I just see the name of the plugin but no icon.
If i click on the name to put it on the task bar or menu of firefox; because there is no icon, the plugin became invisible, and i can't have any interaction with it.

**Comment by rNeomy** [comment]
Can you confirm this on a clean profile?
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by maximedub** [comment]
You have true, with a clean profile all is fine.

thank to you
