### ISSUE TITLE
Feature Request: list "Resources that failed to load"

### ISSUE THREAD

**Issue by RadarNyan** [rNeomy/proxy-switcher#12]
When I was on Chrome, the extension I used for switching proxies is [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega) there is one really useful feature: the ability to show resources that failed to load.

For example, when visiting a website, the website itself loads fine, but some external js used is currently unaccessable. Being able to know that would be extremely useful so I can tweak my PAC file based on what fails to load.

There was a Firefox extension [AutoProxy-ng](https://github.com/hrimfaxi/autoproxy) has a similiar feature that when you press ctrl-alt-v it lists the resources refered on the current tab, but that extension lacks of the ability to use external PAC file (it can only use it's own rules)

**Comment by rNeomy** [comment]
The new version will have badge icon of failed resources. However, it is not as powerful as it could be. Some failed resources are still not detectable. This is the limitation of WebRequest.jsm module. I'll update the extension once this module gets updated.

**Comment by Juan1to** [comment]
/gre/modules/devtools/Loader.jsm 19 null
resource://gre/modules/XPCOMUtils.jsm 273 XPCU_moduleLambda
resource://gre/modules/XPCOMUtils.jsm 198 XPCU_defineLazyGetter/<.get
resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-hjbdm7jjii7lllkqacvgnd3ghge-at-jetpack/lib/firefox/firefox.js 159 null
resource://gre/modules/XPCOMUtils.jsm 198 XPCU_defineLazyGetter/<.get
resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid0-hjbdm7jjii7lllkqacvgnd3ghge-at-jetpack/lib/common.js 141 null
resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js 112 emitOnObject
resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js 89 emit
resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/sandbox.js 356 portEmit
resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js 112 emitOnObject
resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js 89 emit
resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/content/sandbox.js 397 onContentEvent/<
resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/lang/functional/concurrent.js 38 delay/<
resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/timers.js 40 notify
  Deprecated.jsm:79
