### ISSUE TITLE
Feature Request: Automatically switch to a proxy if a pattern is match.

### ISSUE THREAD

**Issue by zkanda** [rNeomy/proxy-switcher#14]
As the title says, something that will automatically switch to a profile if a site I list is detected.

E.g.
For example, a rule like this: `*.google.com/*` will automatically use another profile. While other are not affected.

Thank you for developing this plugin. :+1:

**Comment by rNeomy** [comment]
save this into a text file

```js
const proxy = 'SOCKS5 127.0.0.1:9292';
var hosts = [
	'google.com',
	'*.google.com'
];

function FindProxyForURL (url, host) {
 	for (var i = 0; i < hosts.length; i ++) {
		if (shExpMatch(host, hosts[i])) {
			return proxy;
		}
	}

	return 'DIRECT';
}
```
Then switch to the "automatic" tab and point the input box to this file (file:///....). To find the path, drop the file into your Firefox browser and copy the path in the addessbar

**Comment by zkanda** [comment]
Wow, so fast response, didn't we can do this, it would be good if it can be exposed in the UI. Thanks
