### ISSUE TITLE
Wish list... :)

### ISSUE THREAD

**Issue by limaunion** [rNeomy/proxy-switcher#2]
Hi! I'm a IT admin and have a lot of internal proxies (>15). In order to switch between them I'm currently using the 'Proxy Selector' add-on. I like your UI design much more. My wish list for you add-on would be (1) a better proxy UI list arrangement for that number of proxies and (2) the 'no proxy for' option for each proxy in order to skip internal web servers. Thanks!

**Comment by rNeomy** [comment]
Thanks for the suggestions. Both are now fixed on 0.3.1.1
https://addons.mozilla.org/en-US/firefox/addon/proxy-switcher/versions/
