### ISSUE TITLE
Webextension support?

### ISSUE THREAD

**Issue by hdd60311** [rNeomy/proxy-switcher#28]
Do this addon support webextension before Firefox 57 coming?

**Comment by rNeomy** [comment]
There is a WebExtension version of this add-on which is even more powerful for Chrome browser. But Firefox decided to limit the access to proxy settings. Their API is very limited. I am not sure if I am going to reduce all the modes to a single one and release a new version for FF or not!

**Comment by julienschmidt** [comment]
Have you tried to get in touch with the FF devs to request a more powerful proxy API?
Or is this limitation on purpose?

**Comment by rNeomy** [comment]
This is the port
https://addons.mozilla.org/en-US/firefox/addon/proxy-switcher-and-manager/

Chrome version supports all tabs. Firefox version does not support two tabs. It only works on FF57.

> Have you tried to get in touch with the FF devs to request a more powerful proxy API

Not yet

**Comment by loganmarchione** [comment]
@rNeomy , just to be clear, [this](https://addons.mozilla.org/en-US/firefox/addon/proxy-switcher/) is the old extension, and [this](https://addons.mozilla.org/en-US/firefox/addon/proxy-switcher-and-manager/) is the new one?

Also, what do you mean by this?

> Chrome version supports all tabs. Firefox version does not support two tabs.

**Comment by rNeomy** [comment]
>  just to be clear, this is the old extension, and this is the new one?

Yes, the WebEx on has FF57 compatibility label

> Also, what do you mean by this?

Basically in the WebEx version "Auto-detect Proxy" and "Automatic (PAC)" tabs are not available anymore in the Firefox version. There is no API to activate these two modes.

**Comment by loganmarchione** [comment]
@rNeomy, thanks for clearing that up!

**Comment by amiraliakbari** [comment]
The new (Web Extensions) version is not installable.

**Comment by rNeomy** [comment]
Try it one more time. It just got accepted a few days ago!

**Comment by loganmarchione** [comment]
@rNeomy, the WebExtension is not installable in FF57b3 (just released today). Did the AMO site get updated with your new code?
![image](https://user-images.githubusercontent.com/4955337/30866552-9e022bc4-a2a7-11e7-98cf-911b6f7a8e0d.png)

**Comment by rNeomy** [comment]
I am using "57.0a1" as the min version. Have no idea why it is marked as not compatible. Try to download the XPI and drop it into the addon manager

**Comment by loganmarchione** [comment]
@rNeomy, this is resolved. My fault, not yours.

I have **privacy.resistFingerprinting** set to **true** in my user.js file. This changes my useragent to be the ESR version of Firefox, which is currently v52. According to [this comment](https://www.reddit.com/r/firefox/comments/712c16/firefox_not_deleting_indexeddb_storage_allowing/dn8pycb/), it will eventually be updated to v59.

**Comment by rNeomy** [comment]
Great!

**Comment by jianhuiz** [comment]
Can this API be used to implement PAC?
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/proxy
And the example referenced in the doc:
https://github.com/mdn/webextensions-examples/tree/master/proxy-blocker

**Comment by MonkAlex** [comment]
Any chance to PAC file support in WebExtension? U report bug to mozilla? Must have for me and not found any addon with this for old firefox versions.

**Comment by rNeomy** [comment]
@MonkAlex unfortunately not! The API currently only accepts a limited PAC script that is bundled with the extension. Still, the proxy API is not mature enough to accept remote PACs nor using "Direct" or "Auto Detect" modes.

**Comment by sn260591** [comment]
In ff59 addons can now specify a custom pac file [https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/proxyConfig](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/proxyConfig)

**Comment by rNeomy** [comment]
FF version switched to "proxySettings".
