### ISSUE TITLE
can't see the icon

### ISSUE THREAD

**Issue by flying-whale** [rNeomy/proxy-switcher#3]
Hi,thanks for your work, i try to use this extension's new verson 0.1.3.1 at firefox verson 43.0.4,but after install and reopen firefox,still can't find the icon at toolbar panel.Hope it will help.

**Comment by rNeomy** [comment]
To investigate the problem please follow these steps:
1. Open error console (ctrl + shift + j) and clear it
2. Disable and re-Bengal the extension from extension manager.
3. Is there any new error in the console?

**Comment by flying-whale** [comment]
Yes,it shows:
Unknown property 'speak'.  Declaration dropped. fontello.css:12:7
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. fontello.css:37:25
Unknown property 'user-select'.  Declaration dropped. index.css:12:13
even after i upgrade firefox to V 44.0.1 and reinstall,still can't see it.

**Comment by rNeomy** [comment]
None of these are blocking errors so I am not sure why the extension is not initiating. Can you try the extension on a clean profile, http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

May be there is a conflict with on of your other extensions

**Comment by flying-whale** [comment]
Maybe, i can use this extension with new profile.It is helpful.

**Comment by flying-whale** [comment]
Hi,i find out why can't see the icon.When i set firefox's Options-Pravicy-History as "Never Remember History",after restart,the icon disappear, if set as "Remember History",it shows up.

**Comment by rNeomy** [comment]
Can you confirm this on the clean profile as well?

**Comment by flying-whale** [comment]
Yes,no matter profile is clean or no.

**Comment by not-a-user** [comment]
I can't see the icon either. (Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:44.0) Gecko/20100101 Firefox/44.0) In the error console I get (both with and without the plugin) a couple of (per web page)

    TypeError: this.proxs.resolve is not a function
    dndetails_checkProxy()
     dndetails.js:280
    dndetails_updateLabel()
     dndetails.js:199
    dndetails_onSelectTab()
     dndetails.js:70
     dndetails.js:280:15

Otherwise I'm using SOCKS5 with remote DNS and it is working fine.

**Comment by rNeomy** [comment]
Okay this is fixed by @kousu commit.
You can try it here: 
https://github.com/rNeomy/proxy-switcher/blob/master/builds/jid0-hjBdm7jJii7llLkqacvGnd3gHge@jetpack-0.1.4b1.xpi?raw=true

Download the XPI and drop it into your Firefox. You may need to allow installation of unsigned extensions.

**Comment by not-a-user** [comment]
Confirmed working.

**Comment by rNeomy** [comment]
The new version is submitted for review.
