### ISSUE TITLE
false positive for errors?

### ISSUE THREAD

**Issue by rezad1393** [rNeomy/proxy-switcher#30]
a lot of sites use websockes (like github.com) but when I open then this addon shows an error badge with this info 
"HTTP/1.1 101 Switching Protocols...." 
for the resource.
is this a bug or actually a http error code?

**Comment by rNeomy** [comment]
Do you use Firefox or Chrome?

**Comment by rezad1393** [comment]
firefox

**Comment by rNeomy** [comment]
I am not getting any error while browsing github. Any other example? btw, what is the proxy mode that causes these errors?

**Comment by rezad1393** [comment]
I get this error on github consistently.
but maybe it is my configuration that is different than yours.
even when I choose to connect directly without any pac file I still gen this error on github.

in browser console of firefox in Net tab I see the same message too 
"GET https://live.github.com/_sockets/_many-characters-here_ [HTTP/1.1 101 Switching Protocols 730ms]"
even with this addon disabled  this message appears in the logs there so this message is from firefox but somehow you addon sees it as an error .

**Comment by rNeomy** [comment]
I see. 101 is now an exception. Thanks for the report, will be fixed on the next release
