### ISSUE TITLE
WebExtension cannot proxy DNS requests

### ISSUE THREAD

**Issue by loganmarchione** [rNeomy/proxy-switcher#34]
Using the regular Options -->General-->Network Proxy, I can setup a manual proxy and proxy my DNS though that proxy. I'm able to verify my IP and DNS are the same with a site like http://dnsleak.com.

Using the WebExtension, there is no option to proxy my DNS through the proxy. Even when I check "Proxy DNS when using SOCKS v5" under Options -->General-->Network Proxy, my DNS is not sent through the proxy.

There seems to be a [bug filed](https://bugzilla.mozilla.org/show_bug.cgi?id=1397991) that depended on [another bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1381290) that was fixed in FF57.
> Now that Bug 1381290 has landed in Nightly, the proxy script can return an array of objects instead of a string. The objects have a "proxyDNS" property, which can control the usage of remote DNS (tested with attachment from Bug 1398900 and dnsleaktest.com).

I don't know enough about it to tell if the fix can be enabled with this WebExtension yet, or more changes need made in the FF codebase first...

**Comment by rNeomy** [comment]
Thanks for the bug report. Version 0.1.6 supports "remote dns" like the legacy version.

**Comment by loganmarchione** [comment]
Thanks for the quick turn-around! Verified working!
