### ISSUE TITLE
Support gfwlist？

### ISSUE THREAD

**Issue by ivysrono** [rNeomy/proxy-switcher#4]
gfwlist/gfwlist: The one and only one gfwlist here
https://github.com/gfwlist/gfwlist

This is so important for chinese.
We need to set proxy A for list1(gfwlist)
proxy B for list2……

**Comment by rNeomy** [comment]
To be honest I am not really familiar with gfwlist, but seems like you can easily convert gfwlist file to PAC using something like https://github.com/JinnLynn/genpac. Then you can point the Proxy Switcher to work on the "Automatic" mode using the generated PAC.
