### ISSUE TITLE
Proxy-swtcher stopped working since the moment of upgrade to 0.3.0

### ISSUE THREAD

**Issue by ArcticHaze** [rNeomy/proxy-switcher#46]
At this moment I cannot connect to the internet with neither of the two proxies I use. Actually one of them was on when I upgraded the add on on Firefox 59.0.2 (Win 7 64-bits) and the next page to open gave the "We can’t connect to the server" error. This happens with every page  I try to open why using the "Manual proxy" setting which worked up to the  moment of the upgrade. Switching to "Direct" restores the connection.  Strangely the proxy settings in Firefox Options look 100% but.. they do not work any more.

**Comment by ArcticHaze** [comment]
One more comment: the moment I disable  proxy-switcher and enable the same  proxies manually, in Firefox options, the connections work OK.

**Comment by rNeomy** [comment]
Enable the extension, and set the proxy as usual. Now open FF's default proxy manager and take a look at the settings. Is there anything wrong? Can you take a screenshot of the panel and the settings?

**Comment by SmithersTDI** [comment]
I use Proxy-switcher as well and noticed the same issue when mine was updated to 0.3.0.  The issue on my system is that it is adding `http://` in front of the proxy hostname in the Firefox connection settings.  

So if I set my HTTP proxy to be 127.0.0.1 in the Proxy-switcher, when I look at the Firefox connection settings, my HTTP proxy is `http://127.0.0.1` and Firefox fails to use it.  If I manually remove the `http://`, it works fine.

**Comment by rNeomy** [comment]
@ArcticHaze based on the image, I would say you have forgotten to set SOCKS in the popup. Note that when you set a SOCKS server, there is no need to fill HTTP, FTP, and SSL in the settings page of FF. Only you need to set the SOCKS HOST and Port. In the Proxy Switcher UI, you need to fill all the HTTP, FTP and SSH fields and set the proxy type to SOCKS.

@SmithersTDI are you sure your server is not a SOCKS server? If so make sure in the UI set the type to SOCKS.

**Comment by ArcticHaze** [comment]
I winder how I could forget to fill the SOCKS server if I do not see a
setting for it:



If I click SOCKS 4 or 5 I still do not see a setting for SOCKS host.

I will also repeat that:

1) The add-on worked the very minute I upgraded it (by using the Cogwheel
icon at the top of about:addons) and I changed no settings
2) It works if I manually set only the HTTP  server (so there is no  chance
it is SOCKS)
3) I now switched to SimpleProxy when I need to chose the proxy type and it
works perfectly with "http".

**Comment by rNeomy** [comment]
Set the server and the port in HTTP, SSL, and FTP fields. Set the server type to SOCKS5.

Example:
![screen shot 2018-04-20 at 10 34 51 am](https://user-images.githubusercontent.com/14104614/39033261-7b69c9e2-4486-11e8-82b4-5542bcbf3dfd.png)

**Comment by ArcticHaze** [comment]
And yes, I now see the main difference between my two  screenshots from Comment #4. Proxy switcher really adds http:// to the Firefox setting. The author of Issue #47 is absolutely right.

Please compare the two screenshots carefully, once again.

**Comment by rNeomy** [comment]
@ArcticHaze have you tried the method I suggested?

**Comment by ArcticHaze** [comment]
Setting SOCKS does not help as the Squid proxy is definitely http (I have access to the server as one of it admins and I checked).

Also see points 2)  and 3) in my previous comment (4 comments up)..

**Comment by ArcticHaze** [comment]
Changing to SOCKS. Yes, I tried it yesterday, after the switcher stopped working. I tried to find a working configuration but could not. I re-checked it now even as I knew it will not work. I does not but the long delay shows that with SOCKS, Firefox at least tries to connect something (unlike http).

It also does  not help  with my other proxy which is a http tunnel, I set myself.

**Comment by rNeomy** [comment]
See this post; https://bugzilla.mozilla.org/show_bug.cgi?id=1425535#c2

There is no way to set HTTP, SSL, and FTP without setting the scheme. so basically trying to set HTTP to `127.0.0.1` throws an error. You need to set it with a scheme (e.g.: `http://127.0.0.1`). I know you can set it from the FF UI, but the API does not allow this.

The only field that does not need a scheme is the SOCKS field.

**Comment by Rigido71** [comment]
Just my two cents...
Today, for the first time, FF told me the PSM addon needed my attention upgrading from 0.1.8 to 0.3.1 and tried to send me to an unreachable address, from then I was not able to browse anymore.
FF proxy settings were saying that an addon was managing them but HTTP proxy from PSM has http:// on front and nothing was working.
So, i tried to:

1. export PSM settings
2. remove PSM
3. restart FF
4. re-install PSM (on the toolbar just a blank space appeared , not the PSM icon)
5. restart FF (still no icon and FF proxy settings were "free", no warning about an external manager)
6. Import old settings (same as 5)
7. restart FF

So, now, I'm using a manual setting and no matter what I do it looks like PSM is not installed at all. 

![image](https://user-images.githubusercontent.com/29772377/39044695-3b6f89d4-4491-11e8-9ed2-20aa75931361.png)

**Comment by ManfredSchenkIOSB** [comment]
Same problem here: after upgrade to latest version the plugin does not work anymore

**Comment by rNeomy** [comment]
reverting the release to 0.1.9 (0.3.3 is equal to the 0.1.9) until this issue is fixed. The current config doesn't seem to be sufficient for all users.

@Rigido71 & @ManfredSchenkIOSB are you trying to set a manual SOCKS proxy?

**Comment by ArcticHaze** [comment]
Version 0.3.3.1 Works For Me (with just the HTTP line filled). So it is final proof that it had nothing to do with SOCKS.

By the way the faulty versions did send Firefox one http:// too much (even if it was only one). The new/old version does not affect FF settings but when they were being set by the PS add-on they looked wrong (having the unnecessary http://).

**Comment by Rigido71** [comment]
Installed latest nightly (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0 ID:20180420100056) and icon appeared, no SOCKS, just http proxy and the problem is that PSM tries to set http:// proxy, I can clearly see it keeping FF preferences panel opened.
Keeping Pref panel opened I saw that "System Proxy" and "Auto-detect" are inverted, i'll try to add screenshots.
![2018-04-20_15h01_42](https://user-images.githubusercontent.com/29772377/39052653-0730b1fe-44ad-11e8-9feb-711dc71c4123.png)
![2018-04-20_15h01_51](https://user-images.githubusercontent.com/29772377/39052654-07555fc2-44ad-11e8-896d-f176fbb8407f.png)

**Comment by rNeomy** [comment]
> By the way the faulty versions did send Firefox one http:// too much (even if it was only one).

@ArcticHaze According to the Bugzilla thread that I posted, there is no way to set the HTTP field without "http://" or "https://" schemes! In your case you need to set the IP address in the HTTP field without any schemes being set, right? If so it is not doable at this point using webextension APIs.

btw, I dont undrestant how your server works. Browser can only use HTTP and HTTPS protocols. So how come non of http://.. and https://... works for you (even socks://... doesnt work). I mean forget about this extension. Just set the URLs in the FF network window. When no scheme is set, the default one which is "http://" is used. So if you enter 127.0.0.1 in your address bar, it is euqal to http://127.0.0.1. 

 >  The new/old version does not affect FF settings

Yes, the 0.1.x channel uses a different method. We should eventually switch to the new method, but at this point I am not sure how. That's the reason why I reverted to 0.1.x


>  the problem is that PSM tries to set http:// proxy, I can clearly see it keeping FF preferences panel opened.

@Rigido71  True, there is no way to set the HTTP without having a scheme! see https://bugzilla.mozilla.org/show_bug.cgi?id=1425535#c2

**Comment by ArcticHaze** [comment]
@rNeomy 

Compare once more the two screenshots in the  fourth comment of this bug. In fact I made it easier for yourself taking out of them the crucial parts and putting them side by side.

LEFT: FF Proxy settings set manually. RIGHT: FF proxy settings set by PS

Find three details differing on the pictures:

![proxy04](https://user-images.githubusercontent.com/38537616/39055118-ac35d0e8-44b3-11e8-9509-1bac7e9006b2.png)

All of them are the absence or presence of http://

Tell me, pray, do your FF proxy works if you  set them the way PS does (with http://). Because mine does not. Neither the Squid set up on on the remote server nor the 127.0.0.1 SSH tunnel. 

The moment I delete the http://, the proxy starts working again.

**Comment by ArcticHaze** [comment]
PS. Take a look at any of the multiple examples online of how to set up the proxy in FF. You never have http:// in the settings. Just an example (Internet is full of them):

http://www.youngzsoft.net/ccproxy/upload/firefox501.jpg

**Comment by rNeomy** [comment]
> The moment I delete the http://, the proxy starts working again.

I do understand your point. The problem is the provided API to set the HTTP Proxy first validates the provided value and then applies it. So basically "153.19.130.229:8080" does not pass the validation. I only can provide "http://53.19.130.229:8080" or "https://53.19.130.229:8080". 

I've reported this to Bugzilla. Let's see if there is a workaround for this.

**Comment by ArcticHaze** [comment]
Oh, I see. You mean this?
https://bugzilla.mozilla.org/show_bug.cgi?id=1425535#c2

You should open a new bug instead of posting on a closed one.  Believe me. I've been a component owner on that Bugzilla (even as it was not an important one).

**Comment by rNeomy** [comment]
Here is the new bug report; https://bugzilla.mozilla.org/show_bug.cgi?id=1455636

> BTW, can you confirm that two panels "Direct" and "Autodetect" set the wrong value on FF?

not on the latest commit, though I haven't changed anything regarding the reported issue as far as I can remember. I will check once more when the main issue is resolved.

**Comment by rNeomy** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1455705

**Comment by rNeomy** [comment]
seems like the bug is fixed for FF 60. I just released a new version based on `browser.proxy.settings`. Let me know if there is any issues.
