### ISSUE TITLE
"Manual Proxy" setting incorrect after updating to 0.3.0

### ISSUE THREAD

**Issue by w13508** [rNeomy/proxy-switcher#47]
In version 0.3.0, when I am using "Manual Proxy" and type a HTTP proxy like "proxy.xxx.xx", then I go to the Firefox menu Options->Networks Proxy Setting, the address I typed is automatically added with pre-text of "http://", this makes the proxy setting doens't work.

**Comment by rNeomy** [comment]
Follow #46 inatruction
