### ISSUE TITLE
Support "<local>" in "Direct" box ("No proxy for") on Manual Proxy tab

### ISSUE THREAD

**Issue by edrandall** [rNeomy/proxy-switcher#48]
Firefox uses the keyword "&lt;local&gt;" to indicate that the proxy should be bypassed for all non-qualified hostnames (ie. bare hostname with no dot).  Documented here: https://support.mozilla.org/en-US/kb/connection-settings-firefox

When using ProxySwitcher this bypass no longer seems to work, the bare hostname is sent to our proxy which is unable resolve it and returns Network Error (dns_unresolved_hostname).  

This is a bit of a problem in a corporate environment where we have many local switches, routers and webservers and don't need to be typing a domain name after them.  In any case we have certain hosts (in DMZ) for which we *do* need to add the domain name after them and make the request via the proxy.  So adding *.ourdomain.com to the 'Direct:' list will not help.

See Firefox bug 72444 https://bugzilla.mozilla.org/show_bug.cgi?id=72444 where they spent 8 years arguing and finally came to this &lt;local&gt;  keyword solution!

**Comment by rNeomy** [comment]
The new version uses `browser.proxy.settings` to alter the proxy configs. The issue should have been fixed. Let me know if not.
