### ISSUE TITLE
Replace All chrome.proxy.settings with browserSettings.proxyConfig

### ISSUE THREAD

**Issue by Rictusempra** [rNeomy/proxy-switcher#49]
Since 59+, the proxy setting APIs change a lot.
Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/proxyConfig

(And I observe it not working on those versions  as well)

**Comment by rNeomy** [comment]
The latest commit supports proxyConfig. We will switch when FF60 is released. The implementation on FF59 is buggy.

**Comment by Rictusempra** [comment]
@rNeomy but it has been released now. Am I missing something?

**Comment by loganmarchione** [comment]
Sorry, maybe I'm reading this wrong, but should it be using browserSettings.proxyConfig? The article below makes it seem like it should be using browser.proxy.settings?
https://blog.mozilla.org/addons/2018/05/17/extensions-in-firefox-61/

**Comment by rNeomy** [comment]
> The article below makes it seem like it should be using browser.proxy.settings?

It is changed since FF 60.0

The new release switched to `browser.proxy.settings`
