### ISSUE TITLE
[Feature Request] Proxy API Support

### ISSUE THREAD

**Issue by zero77** [rNeomy/proxy-switcher#53]
Can you please ad support for gimme proxys and/or get proxy list free, they both have a free apt that provides socks4, socks5, http and https all from the APIs.

https://gimmeproxy.com/api/getProxy
https://gimmeproxy.com

https://api.getproxylist.com/proxy
https://getproxylist.com

So users can add a new proxy within the add-on without having to go and find one, unless users want to, in that case they can as normal.

Thanks

**Comment by rNeomy** [comment]
Thanks for the suggestion. We are going to have this new UI.

Manual Tab:

![screen shot](https://user-images.githubusercontent.com/14104614/40577485-fac0b1ac-60f5-11e8-98b0-ae405c631c39.png)

Options Page:

![screen shot](https://user-images.githubusercontent.com/14104614/40577487-fc4c2ce0-60f5-11e8-8a9f-2c73c471a090.png)

**Comment by zero77** [comment]
That looks good, from the image I am guessing users will automatically be able to add proxies based on the filters below?

**Comment by rNeomy** [comment]
Yes, there are two sections. One in the popup to find a proxy server and one on the options page to configure the search queries.
