### ISSUE TITLE
Logs and debug information

### ISSUE THREAD

**Issue by lordloh** [rNeomy/proxy-switcher#63]
I am very concerned about request leaking through wrong proxy. I would like to have an option to enable / disable logs to see what was the input given to the `FindProxyForURL` and what it returned for every URL fetched. Knowing `myIpAddress()` is also useful when using a VPN.

Is there currently a way to get such debug information via developer tools / developer tools > console? Could some such debug feature be added? Or could you suggest me alternate tools / addons to debug my PAC script?

**Comment by rNeomy** [comment]
In Chrome, network tab of the console displays the server IP address for each connection. Is this what you are looking for?
