### ISSUE TITLE
icon shows error count badge despite it being turned off

### ISSUE THREAD

**Issue by bughit** [rNeomy/proxy-switcher#65]
Fx 62, proxy switcher 0.3.9

The error log showsa wss:// request with a 101 reponse

**Comment by sohanlalpareek** [comment]
I missing my filleLeave a comment

**Comment by rNeomy** [comment]
Can you share an example website?

**Comment by bughit** [comment]
1. go to https://www.office.com/
2. click sign-in

this is a clean fx 66.0.3 profile with latest extension (0.4.0)

![image](https://user-images.githubusercontent.com/895588/56684970-cfe0e880-669e-11e9-9677-65c9d2120f24.png)

**Comment by bughit** [comment]
If the error counter is off, it should not be doing any chrome.webRequest interception, an extension should not be using any resources it does not need.
