### ISSUE TITLE
not switching proxy for WSS protocol (WebSocket Secure)

### ISSUE THREAD

**Issue by xambroz** [rNeomy/proxy-switcher#66]
Hello,
it seems the proxy-switcher is not correctly switching proxy for the WSS protocol (WebSocket Secure).
The request like wss://app.any.run/sockjs/304/1qr_8jyf/websocket are trying to access the site directly (or using the global proxy settings in the Preferences/Networking Options/...).
I am not sure what is the status of plaintext WebSocket protocol (ws://), but I guess the situation might be quite the same.

You can test this behaviour on a site https://app.any.run/ .

Switching the proxy by proxy-switcher you can see in the Firefox console errors like:
Firefox can’t establish a connection to the server at wss://app.any.run/sockjs/072/5gjmv8af/websocket.
The connection to wss://app.any.run/sockjs/072/5gjmv8af/websocket was interrupted while the page was loading.

**Comment by rNeomy** [comment]
I am not sure how to test this. How can we tell if it is switched? I am not getting this error on FF66

**Comment by rNeomy** [comment]
please reopen if you have more info
