### ISSUE TITLE
PAC url not working

### ISSUE THREAD

**Issue by freeNestor** [rNeomy/proxy-switcher#69]
I'm using chrome ver 73. I want to use PAC url pointed to a local pac file, but not working. I copy the pac file content to inline and it working. 
I used the url form:   file:///xxx/xxx/xx.txt, is it not supported now?

**Comment by rNeomy** [comment]
It really depends on your browser. Maybe due to security concerns, the `file` scheme is not working. You can easily install a local server and point to the file like `http://127.0.0.1:/..list`

**Comment by freeNestor** [comment]
> It really depends on your browser. Maybe due to security concerns, the `file` scheme is not working. You can easily install a local server and point to the file like `http://127.0.0.1:/..list`

Thanks, it's right. I switched to another browser (Brave Version 0.63.48 Chromium: 74.0.3729.108), it's working.
