### ISSUE TITLE
Manual Proxy: can't select profile with empty FTP Proxy field

### ISSUE THREAD

**Issue by lolilolicon** [rNeomy/proxy-switcher#70]
In a Manual Proxy profile, when HTTP Proxy, SSL Proxy, and FTP Proxy are all filled, fine it works.

But if I leave the "FTP Proxy" host and/or port empty (which tells Firefox to "use direct connection for FTP connections"), I can _save_ the profile, but cannot actually _activate_ it.

IIRC it's the same with the other schemes: you can't leave any empty.

**Comment by rNeomy** [comment]
Thanks for the report. In Firefox it makes sense if you want to use an "HTTP" server only for one or two schemes. However, if you want to use a "SOCKS" server, there is no option to apply it only for one or two schemes; it must be set for all schemes. So in the new fix, you should get the profile back if the server is an "HTTP" server. Still not retrieve the profile if you are on a "SOCKS" server

**Comment by lolilolicon** [comment]
Updated & it works. Thanks!
