### ISSUE TITLE
misleading name change after install

### ISSUE THREAD

**Issue by korc** [rNeomy/proxy-switcher#8]
Before installing the extension, the name of the extension is shown as "Proxy Switcher".
After installing, the name becomes "ipswitcher", which is very confusing.

OS: Linux Debian Jessie
Firefox version: 44.0.2
Add-on version: ipswitcher 0.1.3.1

**Comment by rNeomy** [comment]
Thanks for the report. It is now fixed on 0.1.4
You should get the update soon.
