### ISSUE TITLE
No scrollbar in Pac Script

### ISSUE THREAD

**Issue by VENTO-off** [rNeomy/proxy-switcher#84]
Dear developer,

Thank you for your awesome extension for proxy but I have a problem: I have written JavaScript code and I placed my code in the tab "Pac Script" (screenshot). My code is too long and there is no scrollbar and I can't edit my code. Could you please fix this problem?

P.S. I need to use only the "Inline" option.
![image (1)](https://user-images.githubusercontent.com/13291664/107070085-7f8f3800-67eb-11eb-89d7-d3cdee3c607c.png)

**Comment by rNeomy** [comment]
Thanks for the report. Will get fixed by the next release.
